#
# Executes commands at the start of an interactive session.
#
# Authors:
#   Sorin Ionescu <sorin.ionescu@gmail.com>
#


# Source Prezto.
if [[ -s "${ZDOTDIR:-$HOME}/.zprezto/init.zsh" ]]; then
  source "${ZDOTDIR:-$HOME}/.zprezto/init.zsh"
fi

# Customize to your needs...

# local completions
fpath=(~/.zsh/completion $fpath)

# add local bin to PATH
export PATH="$PATH:$HOME/bin"

POWERLEVEL9K_MODE='nerdfont-complete'

autoload -Uz promptinit
promptinit
prompt powerlevel9k
